### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by 190n** [Modernizr/modernizr-neue#149] opened 2019-07-30 23:57 UTC
Sorry if this is the wrong place to report this; it seemed the most likely. The TLS certificate for modernizr.com expired on July 26, 2019. And since it is using HSTS, most browsers will refuse to connect over an unencrypted connection, so the website is inaccessible.

<img width="907" alt="Screen Shot 2019-07-30 at 4 55 08 PM" src="https://user-images.githubusercontent.com/7763597/62173416-da88ca80-b2ea-11e9-8706-9b5a3381c31d.png">

**Comment by rejas** [comment] 2019-07-31 05:49
Duplicate of https://github.com/Modernizr/Modernizr/issues/2465

**Closed by rejas** 2019-07-31 05:49 UTC
