### ISSUE TITLE
Clicking on toggle from another expanded item is weird

### ISSUE THREAD

**Issue by paulirish** [Modernizr/modernizr-neue#12] opened 2015-09-12 02:29 UTC
when i'm in this state:
![image](https://cloud.githubusercontent.com/assets/39191/9829505/40e9e41e-58bb-11e5-94e2-84c8bce8bb4d.png)

if i click on the plus for input[capture] i expect it to select it. i know my detects well enough that i dont need to open the deets to be sure i want it.

looks like @patrickkettner massaged this behavior in https://github.com/Modernizr/modernizr-neue/blob/0b313457a990ff32dd1bfc6eb0dbbe4186fa2a22/frontend/js/download/Option.js#L59-L70 but i'd suggest we allow the click to select the item, as well as expand it.

**Comment by patrickkettner** [comment] 2015-09-12 02:31
your suggestion is the intended behavior, it just works like shite in the smaller views currently due to the way that the focus is handeled.

should be the highest priority thing to fix, though

**Comment by tomsarduy** [comment] 2015-09-22 18:44
If that's the intended behavior, I think is not what the user expect. Seems like the checkbox don't trigger the toggle event if the current row is already expanded.

**Comment by patrickkettner** [comment] 2015-09-22 18:45
I am saying that what paul says should happen is the intended behavior. what is currently happening is a bug.

**Comment by tomsarduy** [comment] 2015-09-22 18:47
Right @patrickkettner, my bad, I had a bug reading fast ;)

**Comment by patrickkettner** [comment] 2015-09-22 18:47
:D
​

**Comment by patrickkettner** [comment] 2015-11-26 06:37
fixed in 8162cb3fc4aafc58d0d6f46491b6a0724d563be3

**Closed by patrickkettner** 2015-11-26 06:37 UTC
